### ISSUE TITLE
Repo is public, but has no license?

### ISSUE THREAD

**Issue by GClunies** [bufferapp/tracking-plan-kit#17]
Hi Buffer team!

I have been talking with @davidgasquez in the Locally Optimistic Slack about our approaches to write and manage Segment tracking plans as YAML. He was kind enough to share this repo with me (the [Twitter](https://twitter.com/mmcspiritt/status/1427414271797956618?s=20) also brought me here awhile back). I really like what you have built. We have built similar tools at [Surfline](https://www.surfline.com/), but I must admit, your code is a much more elegant solution than the spaghetti scripts I've hacked together! Currently, I use our tools to manage 17 tracking plans across 4 brands, web/iOS/Android - 600+ events and counting!

I think using `tracking-plan-kit` would be a great way to better manage our tracking plans at Surfline! I would love to be able to test out this code, and possibly contribute in the future with additional features/concepts. Perhaps we can develop a best of both worlds from what we have learned and built separately? 

If you are open to contributions, one obstacle is that this repo [does not have a license](https://choosealicense.com/no-permission/), which suggests I can't use, modify, or contribute to this work. Seeing as this is a public repo that has been openly shared across data communities, it _appears_ like you intend for this to be open-source? But, without a license, it is not. If you don't care to share this with others - feel free to ignore this issue.

If you would like to share, would you be wiling to [choose a license](https://choosealicense.com/) and add it to the repo so others (like myself) can use this and contribute without liability concerns?

Really impressive tool you have built here! Would be great to learn from your team and build together :)

**Comment by michael-erasmus** [comment]
Hi @GClunies great to meet you, and thanks for creating the issue. First off just wanted to say I'm a huge fan of Surfline. I live in Santa Cruz, CA and surf as often as I can, so I'm checking the surf reports almost daily. I've been a paid customer for a long time, so great to hear more about what you all are doing over there.

Glad to hear that you're planning on using the tool. 
This repo has been mostly used internally at Buffer, initially we didn't share it much but after some conversations I had on Twitter and people asking about it I shared the code.

As such we didn't even take the effort of adding a license, but I have no issue with creating one! I've created [this PR](https://github.com/bufferapp/tracking-plan-kit/pull/18) to add an MIT license, which I just merged. Let me know if that's sufficient to close this issue.

> I would love to be able to test out this code, and possibly contribute in the future with additional features/concepts. Perhaps we can develop a best of both worlds from what we have learned and built separately?

Sure, happy to have you try it out and see how it works out for your team. I'm not aware of anyone else implementing the tool in production except us so YMMV, there might be some rough edges or it might not do exactly what you need, but contributions are welcome.

It's mostly been working for our needs for a couple of years so even though we're constantly updating our tracking plan, we haven't maintained the tool much. There isn't a lot of documentation. There also some opinionated ways we organize our specific tracking plan baked in to the tool that might not apply generally, like for instance having an [`product` and `area` attribute on events](https://github.com/bufferapp/tracking-plan-kit/blob/master/tracking_plan/json_tracking_plan.py#L91-L100). Also we don't have multiple tracking plans, just one monolith, technically you should be able to manage multiple plans but it's never been tested. 

I while ago I also worked on this [wrapper for Segment's api](https://github.com/bufferapp/segment-config-api) and I thought it might be useful to use that in this repo, but never got round to it :)

That being said, I think you could ignore those Buffer specific features and still make use of this as a way to manage your tracking plan.  Happy to help out with any questions or perhaps even jump on a call sometime to show you how our (non-public) tracking plan is set up to use the tool (we also have some nice ways set up there help to enforce naming conventions and best practices, which could perhaps be extracted into the tool).

**Comment by GClunies** [comment]
Awesome! Thank you @michael-erasmus and @davidgasquez! I will try playing with this on the weekend :)

**Comment by GClunies** [comment]
WOAH - the wrapper for the Segment Config API looks interesting too!

On my end - I am working on some scripts to parse our tracking plans and _automagically_ write the source, staging, and schema files for [dbt](https://www.getdbt.com/) models. Doing this manually in dbt for 600+ events is a major pain in the 🍑. Ultimately, I'd like to share the approach with others, but need improve the MVP and to get permission from the org.

**Comment by michael-erasmus** [comment]
> I can't decide if that's good (easy to separate concerns) or bad (repo structure is complex). 

I think each approach has its pros and cons. The way we have things set up we are sending the same events from multiple sources so it's easier to have on tracking plan, but of course, that means it becomes pretty bloated (which is why we end up adding things like the `area` and `product` and organizing events into different directories).

> I am working on some scripts to parse our tracking plans and automagically write the source, staging, and schema files for dbt models.

Interesting, curious to learn more about that if you do happen to share your approaches. We're not automatically generating models but we've written some dbt macros that will merge events from different sources into a single model (and do some deduplication).

Anyway, closing this issue then if that's OK.
