### ISSUE TITLE
Add a validator

### ISSUE THREAD

**Issue by michael-erasmus** [bufferapp/tracking-plan-kit#5]
The idea would be to add a tracking-plan validate command that can validate yaml tracking plans before we commit/deploy them. This would be a place to ensure our plans are internally consistent and follow our own set of conventions.

Transfered from https://github.com/bufferapp/tracking-plan/issues/10

**Comment by davidgasquez** [comment]
Possibly related with https://github.com/bufferapp/tracking-plan-kit/issues/4 too! :sweat_smile:

**Comment by michael-erasmus** [comment]
Addressed in this PR: https://github.com/bufferapp/tracking-plan-kit/pull/7
